spring:
  #database 접속 정보 및 설정
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/cafe?serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: wjdalsdl11!
