spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/sys?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      username: root
      password: onandon12#
      max-lifetime: 30000
      idle-timeout: 28000
      connection-timeout: 0
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
